#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
photos_path=$3
#timezone=$4
timezone="Europe/Paris"
admin=$5

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a photoshow
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

sudo yunohost app setting photoshow adminusername -v $admin
sudo yunohost app setting photoshow photo_path -v $photos_path


final_path=/var/www/photoshow
thumbnails_path=/var/www/photoshow/thumbnails

sudo mkdir -p $final_path
sudo cp -a ../sources/* $final_path

sudo mkdir -p $photos_path
sudo mkdir -p $thumbnails_path

sudo cp ../conf/config.php $final_path
sudo sed -i "s@yunophotodir@$photos_path@g" $final_path/config.php
sudo sed -i "s@yunothumbdir@$thumbnails_path@g" $final_path/config.php
sudo sed -i "s@yunotimezone@$timezone@g" $final_path/config.php

sudo chown -R www-data:www-data $photos_path
sudo chown -R www-data:www-data $thumbnails_path

# Ajout de l'utilisateur admin
#sudo cp ../conf/Mysql.php $final_path/app/Schema
#sudo sed -i "s/yunoadmin/$admin/g" $final_path/app/Schema/Mysql.php




# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/photoshow.conf


# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf