#!/bin/bash

# Retrieve arguments
domain=$(sudo yunohost app setting photoshow domain)
path=$(sudo yunohost app setting photoshow path)
admin=$(sudo yunohost app setting photoshow adminusername)



# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf